# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-11 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('description', models.TextField(max_length=1000)),
                ('version', models.FloatField(blank=True, null=True)),
                ('main_image', models.URLField(max_length=1000)),
                ('image1', models.URLField(blank=True, max_length=1000, null=True)),
                ('image2', models.URLField(blank=True, max_length=1000, null=True)),
                ('image3', models.URLField(blank=True, max_length=1000, null=True)),
                ('download_link', models.URLField(max_length=1000)),
                ('downloads', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_c', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='download',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='download.Type'),
        ),
    ]
