# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-27 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=10000)),
                ('date', models.DateTimeField()),
                ('author', models.CharField(default='Bibek Bhandari', max_length=50)),
                ('image', models.URLField(max_length=1000)),
                ('slug', models.SlugField(max_length=500, unique=True)),
                ('views', models.IntegerField()),
                ('word_count', models.IntegerField()),
                ('likes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=500)),
                ('image', models.URLField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Category'),
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(related_name='blogs', to='master.Category'),
        ),
    ]
